---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: ((docker_image_tag))

params:
  MAVEN_OPTS:
  MAVEN_CONFIG:
  docker_image_tag: "6"

inputs:
  - name: pcfdemo
  - name: version

outputs:
  - name: build

run:
  path: pcfdemo/ci/tasks/build.sh
  args: [
    --input-dir, pcfdemo,
    --output-dir, build,
    --version-file, version/number,
    --artifactId, pcf-demo,
    --packaging, war
  ]
